# [![Build Status](https://travis-ci.org/dex4er/Starlight.png?branch=master)](https://travis-ci.org/dex4er/Starlight)

language: perl
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq spell
  - cpanm --with-recommends --installdeps --notest --skip-satisfied git://github.com/dex4er/perl-DEXTER-Module-Skeleton
  - cpanm --force --uninstall IO::Socket::SSL
  - cpanm --with-recommends --installdeps --notest --skip-satisfied .
script: ./Dist.SH
perl:
  - 5.18
  - 5.8
branch:
  only:
    - master
