# [![Build Status](https://travis-ci.org/dex4er/Starlight.svg?branch=master)](https://travis-ci.org/dex4er/Starlight)[![CPAN version](https://badge.fury.io/pl/Starlight.svg)](https://metacpan.org/release/Starlight)

sudo: false
language: perl
addons:
  apt:
    packages:
    - aspell
install:
  - cpanm --notest --skip-satisfied App::cpanmw
  - test -n "$TEST_SKIP_EXTRA" || cpanmw --with-recommends --installdeps --notest --skip-satisfied git://github.com/dex4er/perl-DEXTER-Module-Skeleton
  - cpanmw --with-recommends --installdeps --notest --skip-satisfied .
script: ./Dist.SH
matrix:
  include:
  - perl: "5.24"
  - perl: "5.22"
    env: TEST_SKIP_EXTRA=1
  - perl: "5.20"
    env: TEST_SKIP_EXTRA=1
  - perl: "5.18"
    env: TEST_SKIP_EXTRA=1
  - perl: "5.16"
    env: TEST_SKIP_EXTRA=1
  - perl: "5.14"
    env: TEST_SKIP_EXTRA=1
  - perl: "5.12"
    env: TEST_SKIP_EXTRA=1
  - perl: "5.10"
    env: TEST_SKIP_EXTRA=1
  - perl: "5.8"
    env: TEST_SKIP_EXTRA=1
